### PR TITLE
Fix renovate PR

### PR DESCRIPTION
**Pull request by vbontempi**
### Description

This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [terraform-ibm-modules/secrets-manager/ibm](https://registry.terraform.io/modules/terraform-ibm-modules/secrets-manager/ibm) ([source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager)) | module | minor | `1.15.0` -> `1.17.3` |

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Release Notes

<details>
<summary>terraform-ibm-modules/terraform-ibm-secrets-manager (terraform-ibm-modules/secrets-manager/ibm)</summary>

### [`v1.17.3`](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.17.3)

[Compare Source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/compare/v1.17.2...v1.17.3)

##### Bug Fixes

-   **deps:** update terraform-ibm-kms to 4.15.3 ([#&#8203;177](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/177)) ([c17d635](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/commit/c17d635dbbd92bab61d654b93b15f816367a4dce))

### [`v1.17.2`](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.17.2)

[Compare Source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/compare/v1.17.1...v1.17.2)

##### Bug Fixes

-   **deps:** update terraform ibm to latest for the deployable architecture solution ([#&#8203;175](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/175)) ([79f9f8d](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/commit/79f9f8db8086f6c65ef5904d5e3ce66e9629ccce))

### [`v1.17.1`](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.17.1)

[Compare Source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/compare/v1.17.0...v1.17.1)

##### Bug Fixes

-   fixed bug in validation when passing existing SM instance ([#&#8203;173](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/173)) ([282f63f](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/commit/282f63f2faaf7bcb7edba810c10ba31db8da56f1))

### [`v1.17.0`](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.17.0)

[Compare Source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/compare/v1.16.1...v1.17.0)

##### Features

-   added support for enabling Event Notifications integration when passing an existing secrets manager instance ([#&#8203;162](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/162)) ([7c0c8b3](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/commit/7c0c8b35e9fea2f673a0fc523d0211456791ec2c))
-   deps: update minimum required IBM provider to 1.65.0

### [`v1.16.1`](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.16.1)

[Compare Source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/compare/v1.16.0...v1.16.1)

##### Bug Fixes

-   **deps:** update terraform time to latest for the deployable architecture solution ([#&#8203;165](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/165)) ([d0697af](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/commit/d0697af201625020b46c79c5fa23ed58061b6cd2))

### [`v1.16.0`](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.16.0)

[Compare Source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/compare/v1.15.2...v1.16.0)

##### Features

-   added a new [secrets](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/tree/main/modules/secrets) terraform module for adding secrets into secrets groups in an existing Secrets Manager instance ([#&#8203;157](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/157)) ([04c2bc9](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/commit/04c2bc9e198edf331bb8287170f5fbd94e95e302))

### [`v1.15.2`](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.15.2)

[Compare Source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/compare/v1.15.1...v1.15.2)

##### Bug Fixes

-   **deps:** update terraform ibm to latest for the deployable architecture solution ([#&#8203;158](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/158)) ([a858b59](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/commit/a858b59015bcd5863b28e838a70f679d3dc60337))

### [`v1.15.1`](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.15.1)

[Compare Source](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/compare/v1.15.0...v1.15.1)

##### Bug Fixes

-   **deps:** update terraform time to latest for the deployable architecture solution ([#&#8203;153](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/153)) ([a843adf](https://togithub.com/terraform-ibm-modules/terraform-ibm-secrets-manager/commit/a843adf7da7c98961de7de7a0b02d2f3578c9ca2))

</details>

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by shemau — APPROVED** [review]
LGTM

**Comment by ocofaigh** [comment]
No release required (its only an update to the examples)

**Pull request merged**
